version: 2.1
jobs:
  build_server:

    working_directory: ~/repo/server
    docker:
      - image: circleci/openjdk:11-jdk

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout:
          path: ~/repo
      
      - run: pwd; ls -la

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: sbt test:test

      - save_cache:
          paths:
            - ~/.m2
            - ~/.ivy2
          key: v1-dependencies--{{ checksum "build.sbt" }}

      - run: 
          name: Build server
          command: sbt assembly    

  build_web_client:

    working_directory: ~/repo/web-client

    docker:
      - image: cimg/node:16.13.0

    environment:
      CI: false

    steps:
      - checkout:
          path: ~/repo

      - run: pwd; ls -la

      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-deps-
      - run: 
          name: Node install
          command: npm install --save

      - save_cache:
          paths:
            - ~/.m2
            - ~/.ivy2
          key: v1-dependencies--{{ checksum "package-lock.json" }}
      - run: 
          name: Node build
          command: npm run build

workflows:
  build_and_test:
    jobs:
      - build_server
      - build_web_client
