version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.13.0

jobs:
  build_server:

    working_directory: ~/repo/server
    
    docker:
      - image: circleci/openjdk:11-jdk

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:

      - checkout:
          path: ~/repo
      
      - run: pwd; ls -la

      - restore_cache:
          keys:
            - v2-sbt-deps-{{ checksum "build.sbt" }}
            - v2-sbt-deps-

      - run: 
          name: Test
          command: sbt test:test

      - save_cache:
          paths:
            - ~/.m2
            - ~/.ivy2
          key: v2-sbt-deps-{{ checksum "build.sbt" }}

      - run: 
          name: Build server
          command: sbt assembly 
      - persist_to_workspace:
          root: .
          paths:
            - target/scala-2.13/amony.jar

  build_web_client:

    working_directory: ~/repo/web-client

    docker:
      - image: cimg/node:16.13.0

    environment:
      CI: false

    steps:
      
      - checkout:
          path: ~/repo

      - restore_cache:
          keys:
            - v3-npm-deps-{{ checksum "package-lock.json" }}
            - v3-npm-deps-
      
      - run: pwd; ls -la

      - run: 
          name: Node install
          command: npm install --save

      - save_cache:
          paths:
            - node_modules
          key: v3-npm-deps-{{ checksum "package-lock.json" }}
      - run: 
          name: Node build
          command: npm run build

      - persist_to_workspace:
          root: .
          paths:
            - build

  build_docker_image:

    machine: true

    working_directory: ~/repo

    steps:
      - checkout
      - attach_workspace:
          at: .

      - run: mv target server 
      - run: mv build web-client
      - run: pwd; ls -la *

      - gcp-gcr/gcr-auth
      - run:
          -name: Build docker image
          -command: |
              #!/bin/bash -eo pipefail
              docker_tag_args=""

              IFS="," read -ra DOCKER_TAGS <<< "latest"
              for tag in "${DOCKER_TAGS[@]}"; do
                docker_tag_args="$docker_tag_args -t $GOOGLE_COMPUTE_REGION-docker.pkg.dev/$GOOGLE_PROJECT_ID/docker-images/amony/app:${tag}"
              done

              docker build  -f ./Dockerfile $docker_tag_args .
      - run:
          -name: Publish docker image
          -command: |
              #!/bin/bash -eo pipefail
              docker push $GOOGLE_COMPUTE_REGION-docker.pkg.dev/$GOOGLE_PROJECT_ID/docker-images/$GOOGLE_PROJECT_ID/amony/app:latest

              if [ -n "" ]; then
                mkdir -p "$(dirname )"
                docker image inspect --format="{{index .RepoDigests 0}}" $GOOGLE_COMPUTE_REGION-docker.pkg.dev/docker-images/$GOOGLE_PROJECT_ID/amony/app:latest > ""
              fi

workflows:
  build_and_test:
    jobs:
      - build_server
      - build_web_client
      - build_docker_image:
          requires:
            - build_server
            - build_web_client