name: amony

services:
  amony:
    image: europe-west4-docker.pkg.dev/amony-04c85b/docker-images/amony/amony-app:dev
    container_name: amony
    depends_on:
      postgres:
        condition: service_healthy
#    user: "1000:1000"
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      AMONY_ADMIN_USERNAME: "admin"
      AMONY_ADMIN_PASSWORD: "changme"
      AMONY_DATABASE_PROFILE: "slick.jdbc.PostgresProfile$"
      AMONY_DATABASE_URL: "jdbc:postgresql://database:5432/amony"
      AMONY_DATABASE_USERNAME: "postgres"
      AMONY_DATABASE_PASSWORD: "changeme"
    volumes:
      - /Users/merlijn/dev/amony/media:/media
      - appdata:/app/data
    restart: "no"

  postgres:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "amony" ]
      interval: 3s
      timeout: 3s
      retries: 5
    container_name: database
    image: postgres:17.2
    environment:
      POSTGRES_DB: "amony"
      PGUSER: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "changeme"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  appdata: