host = "localhost"
host = ${?DATABASE_HOST}
port = 5432
port = ${?DATABASE_PORT}
database = "amony"
database = ${?DATABASE_NAME}
username = "postgres"
username = ${?DATABASE_USERNAME}
password = "changeme"
password = ${?DATABASE_PASSWORD}
pool-size = 3
pool-size = ${?DATABASE_POOL_SIZE}