import { defineConfig } from 'orval'

// eslint-disable-next-line import/no-default-export -- Orval expects a default export for config
export default defineConfig({
    'amony-api': {
        input: './openapi.yaml',
        output: {
            client: 'react-query',
            target: 'test.ts',
            workspace: 'src/api/generated',
            mode: 'tags-split',
            schemas: 'model',
            prettier: true,
            clean: true,
            override: {
                mutator: {
                    path: '../AxiosInstance.ts',
                    name: 'customAxiosInstance',
                },
                useTypeOverInterfaces: true,
                query: {
                    options: {},
                },
                header: info => [
                    `tslint:disable`,
                    `eslint-disable`,
                    `Generated by orval`,
                    `Do not edit manually.`
                ],
            },
        },
    },
})